use winit::event::VirtualKeyCode;

#[derive(Debug, Hash, Ord, PartialOrd, PartialEq, Eq, Clone, Copy)]
pub struct KeyEvent {
    pub code: u32,
    pub key: VKeyCode,
    pub pressed: bool,    
}

#[derive(Debug, Hash, Ord, PartialOrd, PartialEq, Eq, Clone, Copy)]
#[repr(u32)]
pub enum VKeyCode {
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1.
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    /// Print Screen/SysRq.
    Snapshot,
    /// Scroll Lock.
    Scroll,
    /// Pause/Break key, next to Scroll lock.
    Pause,

    /// `Insert`, next to Backspace.
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    /// The Backspace key, right over Enter.
    BackSpace,
    /// The Enter key.
    Return,
    /// The space bar.
    Space,

    /// The "Compose" key on Linux.
    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    NumpadMultiply,
    NumpadSubtract,

    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    // also called "Next"
    NavigateForward,
    // also called "Prior"
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}
impl From<VirtualKeyCode> for VKeyCode {
    fn from(key: VirtualKeyCode) -> Self {
        match key {
            VirtualKeyCode::Key1 => VKeyCode::Key1,
            VirtualKeyCode::Key2 => VKeyCode::Key2,
            VirtualKeyCode::Key3 => VKeyCode::Key3,
            VirtualKeyCode::Key4 => VKeyCode::Key4,
            VirtualKeyCode::Key5 => VKeyCode::Key5,
            VirtualKeyCode::Key6 => VKeyCode::Key6,
            VirtualKeyCode::Key7 => VKeyCode::Key7,
            VirtualKeyCode::Key8 => VKeyCode::Key8,
            VirtualKeyCode::Key9 => VKeyCode::Key9,
            VirtualKeyCode::Key0 => VKeyCode::Key0,
            VirtualKeyCode::A => VKeyCode::A,
            VirtualKeyCode::B => VKeyCode::B,
            VirtualKeyCode::C => VKeyCode::C,
            VirtualKeyCode::D => VKeyCode::D,
            VirtualKeyCode::E => VKeyCode::E,
            VirtualKeyCode::F => VKeyCode::F,
            VirtualKeyCode::G => VKeyCode::G,
            VirtualKeyCode::H => VKeyCode::H,
            VirtualKeyCode::I => VKeyCode::I,
            VirtualKeyCode::J => VKeyCode::J,
            VirtualKeyCode::K => VKeyCode::K,
            VirtualKeyCode::L => VKeyCode::L,
            VirtualKeyCode::M => VKeyCode::M,
            VirtualKeyCode::N => VKeyCode::N,
            VirtualKeyCode::O => VKeyCode::O,
            VirtualKeyCode::P => VKeyCode::P,
            VirtualKeyCode::Q => VKeyCode::Q,
            VirtualKeyCode::R => VKeyCode::R,
            VirtualKeyCode::S => VKeyCode::S,
            VirtualKeyCode::T => VKeyCode::T,
            VirtualKeyCode::U => VKeyCode::U,
            VirtualKeyCode::V => VKeyCode::V,
            VirtualKeyCode::W => VKeyCode::W,
            VirtualKeyCode::X => VKeyCode::X,
            VirtualKeyCode::Y => VKeyCode::Y,
            VirtualKeyCode::Z => VKeyCode::Z,
            VirtualKeyCode::Escape => VKeyCode::Escape,
            VirtualKeyCode::F1 => VKeyCode::F1,
            VirtualKeyCode::F2 => VKeyCode::F2,
            VirtualKeyCode::F3 => VKeyCode::F3,
            VirtualKeyCode::F4 => VKeyCode::F4,
            VirtualKeyCode::F5 => VKeyCode::F5,
            VirtualKeyCode::F6 => VKeyCode::F6,
            VirtualKeyCode::F7 => VKeyCode::F7,
            VirtualKeyCode::F8 => VKeyCode::F8,
            VirtualKeyCode::F9 => VKeyCode::F9,
            VirtualKeyCode::F10 => VKeyCode::F10,
            VirtualKeyCode::F11 => VKeyCode::F11,
            VirtualKeyCode::F12 => VKeyCode::F12,
            VirtualKeyCode::F13 => VKeyCode::F13,
            VirtualKeyCode::F14 => VKeyCode::F14,
            VirtualKeyCode::F15 => VKeyCode::F15,
            VirtualKeyCode::F16 => VKeyCode::F16,
            VirtualKeyCode::F17 => VKeyCode::F17,
            VirtualKeyCode::F18 => VKeyCode::F18,
            VirtualKeyCode::F19 => VKeyCode::F19,
            VirtualKeyCode::F20 => VKeyCode::F20,
            VirtualKeyCode::F21 => VKeyCode::F21,
            VirtualKeyCode::F22 => VKeyCode::F22,
            VirtualKeyCode::F23 => VKeyCode::F23,
            VirtualKeyCode::F24 => VKeyCode::F24,
            VirtualKeyCode::Snapshot => VKeyCode::Snapshot,
            VirtualKeyCode::Scroll => VKeyCode::Scroll,
            VirtualKeyCode::Pause => VKeyCode::Pause,
            VirtualKeyCode::Insert => VKeyCode::Insert,
            VirtualKeyCode::Home => VKeyCode::Home,
            VirtualKeyCode::Delete => VKeyCode::Delete,
            VirtualKeyCode::End => VKeyCode::End,
            VirtualKeyCode::PageDown => VKeyCode::PageDown,
            VirtualKeyCode::PageUp => VKeyCode::PageUp,
            VirtualKeyCode::Left => VKeyCode::Left,
            VirtualKeyCode::Up => VKeyCode::Up,
            VirtualKeyCode::Right => VKeyCode::Right,
            VirtualKeyCode::Down => VKeyCode::Down,
            VirtualKeyCode::Back => VKeyCode::BackSpace,
            VirtualKeyCode::Return => VKeyCode::Return,
            VirtualKeyCode::Space => VKeyCode::Space,
            VirtualKeyCode::Compose => VKeyCode::Compose,
            VirtualKeyCode::Caret => VKeyCode::Caret,
            VirtualKeyCode::Numlock => VKeyCode::Numlock,
            VirtualKeyCode::Numpad0 => VKeyCode::Numpad0,
            VirtualKeyCode::Numpad1 => VKeyCode::Numpad1,
            VirtualKeyCode::Numpad2 => VKeyCode::Numpad2,
            VirtualKeyCode::Numpad3 => VKeyCode::Numpad3,
            VirtualKeyCode::Numpad4 => VKeyCode::Numpad4,
            VirtualKeyCode::Numpad5 => VKeyCode::Numpad5,
            VirtualKeyCode::Numpad6 => VKeyCode::Numpad6,
            VirtualKeyCode::Numpad7 => VKeyCode::Numpad7,
            VirtualKeyCode::Numpad8 => VKeyCode::Numpad8,
            VirtualKeyCode::Numpad9 => VKeyCode::Numpad9,
            VirtualKeyCode::NumpadAdd => VKeyCode::NumpadAdd,
            VirtualKeyCode::NumpadDivide => VKeyCode::NumpadDivide,
            VirtualKeyCode::NumpadDecimal => VKeyCode::NumpadDecimal,
            VirtualKeyCode::NumpadComma => VKeyCode::NumpadComma,
            VirtualKeyCode::NumpadEnter => VKeyCode::NumpadEnter,
            VirtualKeyCode::NumpadEquals => VKeyCode::NumpadEquals,
            VirtualKeyCode::NumpadMultiply => VKeyCode::NumpadMultiply,
            VirtualKeyCode::NumpadSubtract => VKeyCode::NumpadSubtract,
            VirtualKeyCode::AbntC1 => VKeyCode::AbntC1,
            VirtualKeyCode::AbntC2 => VKeyCode::AbntC2,
            VirtualKeyCode::Apostrophe => VKeyCode::Apostrophe,
            VirtualKeyCode::Apps => VKeyCode::Apps,
            VirtualKeyCode::Asterisk => VKeyCode::Asterisk,
            VirtualKeyCode::At => VKeyCode::At,
            VirtualKeyCode::Ax => VKeyCode::Ax,
            VirtualKeyCode::Backslash => VKeyCode::Backslash,
            VirtualKeyCode::Calculator => VKeyCode::Calculator,
            VirtualKeyCode::Capital => VKeyCode::Capital,
            VirtualKeyCode::Colon => VKeyCode::Colon,
            VirtualKeyCode::Comma => VKeyCode::Comma,
            VirtualKeyCode::Convert => VKeyCode::Convert,
            VirtualKeyCode::Equals => VKeyCode::Equals,
            VirtualKeyCode::Grave => VKeyCode::Grave,
            VirtualKeyCode::Kana => VKeyCode::Kana,
            VirtualKeyCode::Kanji => VKeyCode::Kanji,
            VirtualKeyCode::LAlt => VKeyCode::LAlt,
            VirtualKeyCode::LBracket => VKeyCode::LBracket,
            VirtualKeyCode::LControl => VKeyCode::LControl,
            VirtualKeyCode::LShift => VKeyCode::LShift,
            VirtualKeyCode::LWin => VKeyCode::LWin,
            VirtualKeyCode::Mail => VKeyCode::Mail,
            VirtualKeyCode::MediaSelect => VKeyCode::MediaSelect,
            VirtualKeyCode::MediaStop => VKeyCode::MediaStop,
            VirtualKeyCode::Minus => VKeyCode::Minus,
            VirtualKeyCode::Mute => VKeyCode::Mute,
            VirtualKeyCode::MyComputer => VKeyCode::MyComputer,
            VirtualKeyCode::NavigateForward => VKeyCode::NavigateForward,
            VirtualKeyCode::NavigateBackward => VKeyCode::NavigateBackward,
            VirtualKeyCode::NextTrack => VKeyCode::NextTrack,
            VirtualKeyCode::NoConvert => VKeyCode::NoConvert,
            VirtualKeyCode::OEM102 => VKeyCode::OEM102,
            VirtualKeyCode::Period => VKeyCode::Period,
            VirtualKeyCode::PlayPause => VKeyCode::PlayPause,
            VirtualKeyCode::Plus => VKeyCode::Plus,
            VirtualKeyCode::Power => VKeyCode::Power,
            VirtualKeyCode::PrevTrack => VKeyCode::PrevTrack,
            VirtualKeyCode::RAlt => VKeyCode::RAlt,
            VirtualKeyCode::RBracket => VKeyCode::RBracket,
            VirtualKeyCode::RControl => VKeyCode::RControl,
            VirtualKeyCode::RShift => VKeyCode::RShift,
            VirtualKeyCode::RWin => VKeyCode::RWin,
            VirtualKeyCode::Semicolon => VKeyCode::Semicolon,
            VirtualKeyCode::Slash => VKeyCode::Slash,
            VirtualKeyCode::Sleep => VKeyCode::Sleep,
            VirtualKeyCode::Stop => VKeyCode::Stop,
            VirtualKeyCode::Sysrq => VKeyCode::Sysrq,
            VirtualKeyCode::Tab => VKeyCode::Tab,
            VirtualKeyCode::Underline => VKeyCode::Underline,
            VirtualKeyCode::Unlabeled => VKeyCode::Unlabeled,
            VirtualKeyCode::VolumeDown => VKeyCode::VolumeDown,
            VirtualKeyCode::VolumeUp => VKeyCode::VolumeUp,
            VirtualKeyCode::Wake => VKeyCode::Wake,
            VirtualKeyCode::WebBack => VKeyCode::WebBack,
            VirtualKeyCode::WebFavorites => VKeyCode::WebFavorites,
            VirtualKeyCode::WebForward => VKeyCode::WebForward,
            VirtualKeyCode::WebHome => VKeyCode::WebHome,
            VirtualKeyCode::WebRefresh => VKeyCode::WebRefresh,
            VirtualKeyCode::WebSearch => VKeyCode::WebSearch,
            VirtualKeyCode::WebStop => VKeyCode::WebStop,
            VirtualKeyCode::Yen => VKeyCode::Yen,
            VirtualKeyCode::Copy => VKeyCode::Copy,
            VirtualKeyCode::Paste => VKeyCode::Paste,
            VirtualKeyCode::Cut => VKeyCode::Cut,
        }
    }
}