use winit::keyboard::KeyCode;

#[derive(Debug, Hash, Ord, PartialOrd, PartialEq, Eq, Clone, Copy)]
pub struct KeyEvent {
    pub code: u32,
    pub key: LgKeyCode,
    pub pressed: bool,    
}

#[derive(Debug, Hash, Ord, PartialOrd, PartialEq, Eq, Clone, Copy)]
#[repr(u32)]
pub enum LgKeyCode {
    None,
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1.
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    /// Print Screen/SysRq.
    Snapshot,
    /// Scroll Lock.
    Scroll,
    /// Pause/Break key, next to Scroll lock.
    Pause,

    /// `Insert`, next to Backspace.
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,
    PrintScreen,

    Left,
    Up,
    Right,
    Down,

    Fn,

    CapsLock,

    /// The Backspace key, right over Enter.
    BackSpace,
    /// The Enter key.
    Enter,
    /// The space bar.
    Space,

    /// The "Compose" key on Linux.
    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadAdd,
    NumpadDivide,
    NumpadDecimal,
    NumpadComma,
    NumpadEnter,
    NumpadEqual,
    NumpadMultiply,
    NumpadSubtract,

    AbntC1,
    AbntC2,
    Apostrophe,
    Apps,
    Asterisk,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Quote,
    BQuote,
    Convert,
    Equal,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LSuper,
    RSuper,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Mute,
    MyComputer,
    // also called "Next"
    NavigateForward,
    // also called "Prior"
    NavigateBackward,
    NextTrack,
    NoConvert,
    OEM102,
    Period,
    PlayPause,
    Plus,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}
impl From<winit::keyboard::KeyCode> for LgKeyCode {
    fn from(key: winit::keyboard::KeyCode) -> Self {
        match key {
            KeyCode::Backquote => LgKeyCode::BQuote,
            KeyCode::Backslash => LgKeyCode::Backslash,
            KeyCode::BracketLeft => LgKeyCode::LBracket,
            KeyCode::BracketRight => LgKeyCode::RBracket,
            KeyCode::Comma => LgKeyCode::Comma,
            KeyCode::Digit0 => LgKeyCode::Key0,
            KeyCode::Digit1 => LgKeyCode::Key1,
            KeyCode::Digit2 => LgKeyCode::Key2,
            KeyCode::Digit3 => LgKeyCode::Key3,
            KeyCode::Digit4 => LgKeyCode::Key4,
            KeyCode::Digit5 => LgKeyCode::Key5,
            KeyCode::Digit6 => LgKeyCode::Key6,
            KeyCode::Digit7 => LgKeyCode::Key7,
            KeyCode::Digit8 => LgKeyCode::Key8,
            KeyCode::Digit9 => LgKeyCode::Key9,
            KeyCode::Equal => LgKeyCode::Equal,
            // KeyCode::IntlBackslash => todo!(),
            // KeyCode::IntlRo => todo!(),
            KeyCode::IntlYen => LgKeyCode::Yen,
            KeyCode::KeyA => LgKeyCode::A,
            KeyCode::KeyB => LgKeyCode::B,
            KeyCode::KeyC => LgKeyCode::C,
            KeyCode::KeyD => LgKeyCode::D,
            KeyCode::KeyE => LgKeyCode::E,
            KeyCode::KeyF => LgKeyCode::F,
            KeyCode::KeyG => LgKeyCode::G,
            KeyCode::KeyH => LgKeyCode::H,
            KeyCode::KeyI => LgKeyCode::I,
            KeyCode::KeyJ => LgKeyCode::J,
            KeyCode::KeyK => LgKeyCode::K,
            KeyCode::KeyL => LgKeyCode::L,
            KeyCode::KeyM => LgKeyCode::M,
            KeyCode::KeyN => LgKeyCode::N,
            KeyCode::KeyO => LgKeyCode::O,
            KeyCode::KeyP => LgKeyCode::P,
            KeyCode::KeyQ => LgKeyCode::Q,
            KeyCode::KeyR => LgKeyCode::R,
            KeyCode::KeyS => LgKeyCode::S,
            KeyCode::KeyT => LgKeyCode::T,
            KeyCode::KeyU => LgKeyCode::U,
            KeyCode::KeyV => LgKeyCode::V,
            KeyCode::KeyW => LgKeyCode::W,
            KeyCode::KeyX => LgKeyCode::X,
            KeyCode::KeyY => LgKeyCode::Y,
            KeyCode::KeyZ => LgKeyCode::Z,
            KeyCode::Minus => LgKeyCode::Minus,
            KeyCode::Period => LgKeyCode::Period,
            KeyCode::Quote => LgKeyCode::Quote,
            KeyCode::Semicolon => LgKeyCode::Semicolon,
            KeyCode::Slash => LgKeyCode::Slash,
            KeyCode::AltLeft => LgKeyCode::LAlt,
            KeyCode::AltRight => LgKeyCode::RAlt,
            KeyCode::Backspace => LgKeyCode::BackSpace,
            KeyCode::CapsLock => LgKeyCode::CapsLock,
            // KeyCode::ContextMenu => todo!(),
            KeyCode::ControlLeft => LgKeyCode::LControl,
            KeyCode::ControlRight => LgKeyCode::RControl,
            KeyCode::Enter => LgKeyCode::Enter,
            KeyCode::SuperLeft => LgKeyCode::LSuper,
            KeyCode::SuperRight => LgKeyCode::RSuper,
            KeyCode::ShiftLeft => LgKeyCode::LShift,
            KeyCode::ShiftRight => LgKeyCode::RShift,
            KeyCode::Space => LgKeyCode::Space,
            KeyCode::Tab => LgKeyCode::Tab,
            KeyCode::Convert => LgKeyCode::Convert,
            KeyCode::KanaMode => LgKeyCode::Kana,
            // KeyCode::Lang1 => todo!(),
            // KeyCode::Lang2 => todo!(),
            // KeyCode::Lang3 => todo!(),
            // KeyCode::Lang4 => todo!(),
            // KeyCode::Lang5 => todo!(),
            KeyCode::NonConvert => LgKeyCode::NoConvert,
            KeyCode::Delete => LgKeyCode::Delete,
            KeyCode::End => LgKeyCode::End,
            // KeyCode::Help => todo!(),
            KeyCode::Home => LgKeyCode::Home,
            KeyCode::Insert => LgKeyCode::Insert,
            KeyCode::PageDown => LgKeyCode::PageDown,
            KeyCode::PageUp => LgKeyCode::PageUp,
            KeyCode::ArrowDown => LgKeyCode::Down,
            KeyCode::ArrowLeft => LgKeyCode::Left,
            KeyCode::ArrowRight => LgKeyCode::Right,
            KeyCode::ArrowUp => LgKeyCode::Up,
            KeyCode::NumLock => LgKeyCode::Numlock,
            KeyCode::Numpad0 => LgKeyCode::Numpad0,
            KeyCode::Numpad1 => LgKeyCode::Numpad1,
            KeyCode::Numpad2 => LgKeyCode::Numpad2,
            KeyCode::Numpad3 => LgKeyCode::Numpad3,
            KeyCode::Numpad4 => LgKeyCode::Numpad4,
            KeyCode::Numpad5 => LgKeyCode::Numpad5,
            KeyCode::Numpad6 => LgKeyCode::Numpad6,
            KeyCode::Numpad7 => LgKeyCode::Numpad7,
            KeyCode::Numpad8 => LgKeyCode::Numpad8,
            KeyCode::Numpad9 => LgKeyCode::Numpad9,
            KeyCode::NumpadAdd => LgKeyCode::NumpadAdd,
            // KeyCode::NumpadBackspace => todo!(),
            // KeyCode::NumpadClear => todo!(),
            // KeyCode::NumpadClearEntry => todo!(),
            KeyCode::NumpadComma => LgKeyCode::NumpadComma,
            KeyCode::NumpadDecimal => LgKeyCode::NumpadDecimal,
            KeyCode::NumpadDivide => LgKeyCode::NumpadDivide,
            KeyCode::NumpadEnter => LgKeyCode::NumpadEnter,
            KeyCode::NumpadEqual => LgKeyCode::NumpadEqual,
            // KeyCode::NumpadHash => todo!(),
            // KeyCode::NumpadMemoryAdd => todo!(),
            // KeyCode::NumpadMemoryClear => todo!(),
            // KeyCode::NumpadMemoryRecall => todo!(),
            // KeyCode::NumpadMemoryStore => todo!(),
            // KeyCode::NumpadMemorySubtract => todo!(),
            KeyCode::NumpadMultiply => LgKeyCode::NumpadMultiply,
            // KeyCode::NumpadParenLeft => todo!(),
            // KeyCode::NumpadParenRight => todo!(),
            // KeyCode::NumpadStar => todo!(),
            KeyCode::NumpadSubtract => LgKeyCode::NumpadSubtract,
            KeyCode::Escape => LgKeyCode::Escape,
            KeyCode::Fn => LgKeyCode::Fn,
            // KeyCode::FnLock => todo!(),
            KeyCode::PrintScreen => LgKeyCode::PrintScreen,
            // KeyCode::ScrollLock => todo!(),
            KeyCode::Pause => LgKeyCode::Pause,
            KeyCode::BrowserBack => LgKeyCode::WebBack,
            KeyCode::BrowserFavorites => LgKeyCode::WebFavorites,
            KeyCode::BrowserForward => LgKeyCode::WebForward,
            KeyCode::BrowserHome => LgKeyCode::WebHome,
            KeyCode::BrowserRefresh => LgKeyCode::WebRefresh,
            KeyCode::BrowserSearch => LgKeyCode::WebSearch,
            KeyCode::BrowserStop => LgKeyCode::WebStop,
            // KeyCode::Eject => todo!(),
            // KeyCode::LaunchApp1 => todo!(),
            // KeyCode::LaunchApp2 => todo!(),
            // KeyCode::LaunchMail => todo!(),
            KeyCode::MediaPlayPause => LgKeyCode::PlayPause,
            KeyCode::MediaSelect => LgKeyCode::MediaSelect,
            KeyCode::MediaStop => LgKeyCode::MediaStop,
            // KeyCode::MediaTrackNext => todo!(),
            // KeyCode::MediaTrackPrevious => todo!(),
            KeyCode::Power => LgKeyCode::Power,
            KeyCode::Sleep => LgKeyCode::Sleep,
            KeyCode::AudioVolumeDown => LgKeyCode::VolumeDown,
            KeyCode::AudioVolumeMute => LgKeyCode::Mute,
            KeyCode::AudioVolumeUp => LgKeyCode::VolumeUp,
            KeyCode::WakeUp => LgKeyCode::Wake,
            // KeyCode::Meta => todo!(),
            // KeyCode::Hyper => todo!(),
            // KeyCode::Turbo => todo!(),
            // KeyCode::Abort => todo!(),
            // KeyCode::Resume => todo!(),
            // KeyCode::Suspend => todo!(),
            // KeyCode::Again => todo!(),
            KeyCode::Copy => LgKeyCode::Copy,
            KeyCode::Cut => LgKeyCode::Cut,
            // KeyCode::Find => todo!(),
            // KeyCode::Open => todo!(),
            KeyCode::Paste => LgKeyCode::Paste,
            // KeyCode::Props => todo!(),
            // KeyCode::Select => todo!(),
            // KeyCode::Undo => todo!(),
            // KeyCode::Hiragana => todo!(),
            // KeyCode::Katakana => todo!(),
            KeyCode::F1 => LgKeyCode::F1,
            KeyCode::F2 => LgKeyCode::F2,
            KeyCode::F3 => LgKeyCode::F3,
            KeyCode::F4 => LgKeyCode::F4,
            KeyCode::F5 => LgKeyCode::F5,
            KeyCode::F6 => LgKeyCode::F6,
            KeyCode::F7 => LgKeyCode::F7,
            KeyCode::F8 => LgKeyCode::F8,
            KeyCode::F9 => LgKeyCode::F9,
            KeyCode::F10 => LgKeyCode::F10,
            KeyCode::F11 => LgKeyCode::F11,
            KeyCode::F12 => LgKeyCode::F12,
            KeyCode::F13 => LgKeyCode::F13,
            KeyCode::F14 => LgKeyCode::F14,
            KeyCode::F15 => LgKeyCode::F15,
            KeyCode::F16 => LgKeyCode::F16,
            KeyCode::F17 => LgKeyCode::F17,
            KeyCode::F18 => LgKeyCode::F18,
            KeyCode::F19 => LgKeyCode::F19,
            KeyCode::F20 => LgKeyCode::F20,
            KeyCode::F21 => LgKeyCode::F21,
            KeyCode::F22 => LgKeyCode::F22,
            KeyCode::F23 => LgKeyCode::F23,
            KeyCode::F24 => LgKeyCode::F24,
            // KeyCode::F25 => todo!(),
            // KeyCode::F26 => todo!(),
            // KeyCode::F27 => todo!(),
            // KeyCode::F28 => todo!(),
            // KeyCode::F29 => todo!(),
            // KeyCode::F30 => todo!(),
            // KeyCode::F31 => todo!(),
            // KeyCode::F32 => todo!(),
            // KeyCode::F33 => todo!(),
            // KeyCode::F34 => todo!(),
            // KeyCode::F35 => todo!(),
            _ => LgKeyCode::None,
        }
    }
}